### ISSUE TITLE
Processing order

### ISSUE THREAD

**Issue by jaymecd** [simple-es/message-bus-bridge#1]
As I get right, event should be persisted first. And only after it's successfully saved, event is dispatched via message bus. Otherwise it does not guarantee consistency and may lead to unpredictable behaviour.

**Comment by ramondelafuente** [comment]
I'm using this approach in conjunction with MessageBus middleware:

https://github.com/SimpleBus/MessageBus/blob/master/src/Recorder/HandlesRecordedMessagesMiddleware.php

This only "handles" the domain messages if the command was completed properly. So putting the messages on the bus does not mean they are also handled - if an exception occurs the messages will be erased.

Does that make sense? (I'm still exploring these angles a bit, so your points are very welcome to me)

**Comment by jaymecd** [comment]
I'm afraid I miss something, so could you pls provide working sample of how `simple-es`, `simplebus` and `this-bridge` work together?

**Comment by jaspernbrouwer** [comment]
I'll see if I can write something up quickly tomorrow (mobile again).

I'm also busy writing documentation for the libraries, so questions like this will be properly addressed. This is all done in free/spare time, it will come in due time :)

But thanks for your interest, any (critical) feedback is welcome!

**Comment by jaspernbrouwer** [comment]
Btw, when using MessageBusBridge and DoctrineDBALBridge, I also recommend [JNB\DoctrineDBALBridge](https://github.com/jaspernbrouwer/DoctrineDBALBridge) for transactional consistency.

**Comment by jaspernbrouwer** [comment]
A little knowledge of how SimpleBus\MessageBus works is advised.

So `SimpleES\MessageBusBridge\Event\Store\Decorator\MessageRecordingDecorator` has a `SimpleBus\Message\Recorder\RecordsMessages` as dependency. When `MessageRecordingDecorator::commit()` is called, it will pass all the events (`EventEnvelope`s to be exact) to `RecordsMessages`.

You're correct that the actual Event Store is the endpoint of the decorator chain, so the above will indeed happen before the events reach that store.

But `RecordsMessages` is merely a sort of tape. It only records messages/events, but does not inject them into a message/event -bus.

You should set up `SimpleBus\Message\Recorder\HandlesRecordedMessagesMiddleware` as a **command**-bus middleware, passing an event-bus as dependency (together with `RecordsMessages` of course). Now when (and only when) a command handler is completely finished, thus the events have been stored successfully, will `HandlesRecordedMessagesMiddleware` hand the events over to the event-bus.

I hope this makes sense :)

PS: I've been considering changing the decorator style of `StoresEvents` into middlewares. Please [read about it here](https://github.com/simple-es/event-sourcing/issues/4). I'd appreciate some advise on this!

**Comment by jaymecd** [comment]
Tnx for explanation
